server:
    port: 8181
spring:
  application:
    name: game-server
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: postgresql
app:
  authorization:
    salt: "gameserver"