server:
    port: 8182
spring:
  application:
    name: core-gameplay-service

app:
  player:
    initial-health: 100
    damage: 10
    speed: 5
  room:
    first:
      x: -2
      y: -1
    second:
      x: 2
      y: 1